server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#  server:
#       enable-self-preservation: false  # 设为false，关闭自我保护
#       eviction-interval-timer-in-ms: 4000  # 清理间隔（单位毫秒，默认是60*1000）