server:
  port: 8765
spring:
  application:
    name: service-feign-hystrix


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


feign:
  hystrix:
    enabled: true


